/**
 * Generates supabase/seed.sql from the local catalogue so the database always
 * mirrors src/data. Re-run after editing brands.ts, cars.ts or badges.ts:
 *
 *   node scripts/generate-seed.mjs
 *
 * It reads the exported array literals directly (they are plain data, no logic),
 * which keeps the script dependency-free.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Pulls `export const NAME: Type = [ ... ];` out of a TS module and evaluates it. */
function readArray(relativePath, name) {
  const source = readFileSync(join(root, relativePath), 'utf8');
  const start = source.indexOf(`export const ${name}`);
  if (start === -1) throw new Error(`${name} not found in ${relativePath}`);

  // Skip past the type annotation (`: Car[]`) to the `=` before the literal.
  const assign = source.indexOf('=', start);
  const open = source.indexOf('[', assign);
  let depth = 0;
  let end = -1;

  for (let i = open; i < source.length; i += 1) {
    if (source[i] === '[') depth += 1;
    else if (source[i] === ']') {
      depth -= 1;
      if (depth === 0) {
        end = i;
        break;
      }
    }
  }

  if (end === -1) throw new Error(`Unterminated array for ${name}`);
  return new Function(`return ${source.slice(open, end + 1)};`)();
}

const quote = (value) => `'${String(value).replace(/'/g, "''")}'`;
const nullable = (value) => (value === null || value === undefined ? 'null' : value);
const array = (values) =>
  values.length ? `array[${values.map(quote).join(', ')}]::text[]` : `'{}'::text[]`;

const brands = readArray('src/data/brands.ts', 'BRANDS');
const cars = readArray('src/data/cars.ts', 'CARS');

const COLLECTION_SIZE = 5;

const lines = [
  '-- Generated by scripts/generate-seed.mjs — do not edit by hand.',
  '',
  '-- collections (one per brand)',
  'insert into public.collections (id, name, country, size, aliases) values',
  brands
    .map(
      (b) =>
        `  (${quote(b.id)}, ${quote(b.name)}, ${quote(b.country)}, ${COLLECTION_SIZE}, ${array(b.aliases)})`,
    )
    .join(',\n') +
    '\non conflict (id) do update set name = excluded.name, country = excluded.country, aliases = excluded.aliases;',
  '',
  '-- cars',
  'insert into public.cars (id, collection_id, model, generation, year_from, year_to, power, country, price_new, rarity, aliases) values',
  cars
    .map(
      (c) =>
        `  (${quote(c.id)}, ${quote(c.brandId)}, ${quote(c.model)}, ${quote(c.generation)}, ` +
        `${c.yearFrom}, ${nullable(c.yearTo)}, ${c.power}, ${quote(c.country)}, ${c.priceNew}, ` +
        `${quote(c.rarity)}, ${array(c.aliases)})`,
    )
    .join(',\n') +
    '\non conflict (id) do update set model = excluded.model, generation = excluded.generation, ' +
    'year_from = excluded.year_from, year_to = excluded.year_to, power = excluded.power, ' +
    'country = excluded.country, price_new = excluded.price_new, rarity = excluded.rarity, ' +
    'aliases = excluded.aliases;',
  '',
  '-- badges (catalogue only — unlocks are derived from garage)',
  'insert into public.badges (id, name, description, kind, target, collection_id) values',
  [
    `  ('cars-100', '100 voitures', 'Ajoute 100 voitures à ton garage', 'cars', 100, null)`,
    `  ('legendary-10', '10 Legendary', 'Découvre 10 voitures Legendary', 'rarity', 10, null)`,
    `  ('scans-50', '50 scans', 'Lance 50 scans', 'scans', 50, null)`,
    `  ('xp-1000', '1000 XP', 'Accumule 1000 XP', 'xp', 1000, null)`,
    ...brands.map(
      (b) =>
        `  (${quote(`collector-${b.id}`)}, ${quote(`${b.name} Collector`)}, ` +
        `${quote(`Réunis les ${COLLECTION_SIZE} ${b.name}`)}, 'collection', ${COLLECTION_SIZE}, ${quote(b.id)})`,
    ),
  ].join(',\n') +
    '\non conflict (id) do update set name = excluded.name, description = excluded.description, ' +
    'target = excluded.target;',
  '',
];

writeFileSync(join(root, 'supabase/seed.sql'), lines.join('\n'));
console.log(`seed.sql written — ${brands.length} collections, ${cars.length} cars`);
